### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by SAWRJJ** [josephattalla/Basketball-Shot-Detection#1]
Hi, you provide a great method to detect the basketball, I also read the Avi Shah's work. But he didn't provide a sufficient dataset to train, I want to know how you could train a wonderful pt and which dataset you chosen.

**Comment by josephattalla** [comment]
I have added the notebook I used to train the model I used, `training.ipynb`. I ran it on Google Colab utilizing their hardware acceleration. After training go to `./runs/detect/train/weights` to find the `.pt` files. You can find plenty of datasets to train at [https://universe.roboflow.com/browse/sports/basketball](https://universe.roboflow.com/browse/sports/basketball).

**Comment by SAWRJJ** [comment]
Thank you very much
